### ISSUE TITLE
Element Text Area

### ISSUE THREAD

**Issue by alenamiklos8** [vtex/onda#34]
Fiz algumas versões de Text Area, tenho como favorita o primeiro da linha 2, mas o tom de cinza pode acabar confundindo como desabilitado. Variei com o fundo azul, mas o Tachyons só disponibiliza 3 tons, se fosse trabalhar com fundo colorido seria um azul mais claro.
Gostaria de feedbacks e sua preferência dentro dessas opções.

![textfield](https://cloud.githubusercontent.com/assets/24416479/21866364/0edabbb4-d831-11e6-84f9-e7d322b85ee5.png)

**Comment by dfosco** [comment]
Fechado, discussão segue no https://github.com/vtex/onda/issues/34
