### ISSUE TITLE
Breadcrumb

### ISSUE THREAD

**Issue by alenamiklos8** [vtex/onda#41]
# Estudos de estilo
![captura de tela 2017-01-18 as 18 29 54](https://cloud.githubusercontent.com/assets/24416479/22081797/35a2a9d4-ddac-11e6-89a6-3440f2406426.png)

# Versão final
![captura de tela 2017-01-18 as 18 30 01](https://cloud.githubusercontent.com/assets/24416479/22081806/3e4e7996-ddac-11e6-8529-ac52a20346cc.png)

**Comment by zehfernandes** [comment]
Faltou representar os estados deste breadcrump.

Quando estou no último nivel todos os outros ficam apagados?
E quando estou no primeiro nível e tenho outros pela frente eles também ficam apagados?

Senti falta de representar a noção de progresso. Algo como:
<img width="637" alt="screen shot 2017-01-19 at 11 48 01 am" src="https://cloud.githubusercontent.com/assets/1891339/22109051/2e0227a4-de3d-11e6-88db-e8bc8dbe3d67.png">

**Comment by brenoc** [comment]
@zehfernandes isso configura um breadcrumb?

Pra mim é so por onde a pessoa passou, é realmente a trilha de migalhas de pão da historinha la. Ou seja, ela está sempre no ultimo nivel.

Acho que o que vc esta falando é um outro componente, com outro proposito. Que é como um progresso ou algo do tipo.

**Comment by zehfernandes** [comment]
@brenoc Realmente a nomenclatura está errada. Este dev ser um outro componente, como progress flow, algo assim.
