### ISSUE TITLE
Popover

### ISSUE THREAD

**Issue by alenamiklos8** [vtex/onda#44]
![captura de tela 2017-01-18 as 19 21 47](https://cloud.githubusercontent.com/assets/24416479/22083514/8d5a2cb8-ddb3-11e6-9c04-47d46fa9140e.png)

## exemplo:
![captura de tela 2017-01-18 as 19 24 15](https://cloud.githubusercontent.com/assets/24416479/22083553/c4566844-ddb3-11e6-9f53-b304aeeaf567.png)

**Comment by zehfernandes** [comment]
- Atenção ao border-radius
- Essa shadow pode ser menos percebida e mais sentida.
